author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
description: |
  Provides a type-safe encoding of the Rollbar API.
  Also provides functions to communicate with the Rollbar API.
extra-source-files:
  - CHANGELOG.md
  - README.md
github: joneshf/rollbar-hs
library:
  dependencies:
    - aeson >= 1.0 && < 1.5
    - base >= 4.9 && < 5
    - bytestring >= 0.10 && < 0.11
    - case-insensitive >= 1.2 && < 1.3
    - hostname >= 1.0 && < 1.1
    - http-client >= 0.5 && < 0.6
    - http-conduit >= 2.2 && < 2.4
    - http-types >= 0.9 && < 0.13
    - network >= 2.6 && < 2.7
    - text >= 1.2 && < 1.3
    - time >= 1.6 && < 1.9
    - unordered-containers >= 0.2 && < 0.3
    - uuid >= 1.3 && < 1.4
  source-dirs: src
license: BSD3
maintainer: jones3.hardy@gmail.com
name: rollbar-hs
synopsis: Core Rollbar data types and APIs.
tests:
  doc-test:
    dependencies:
      - QuickCheck >= 2.9
      - aeson >= 1.0
      - base >= 4.9
      - bytestring >= 0.10
      - case-insensitive >= 1.2
      - containers >= 0.5
      - hspec >= 2.4
      - hspec-golden-aeson >= 0.2
      - lens >= 4.15
      - lens-aeson >= 1.0
      - rollbar-hs
      - text >= 1.2
    main: Main.hs
    source-dirs: test
version: '0.3.0.1'
