author: Hardy Jones
category: Logging
copyright: 2018 Hardy Jones
description:
  Integrates Katip with Rollbar to automatically send items to Rollbar.
extra-source-files:
  - README.md
github: joneshf/katip-rollbar
library:
  dependencies:
    - aeson >= 1.2 && < 1.4
    - async >= 2.1 && < 2.3
    - base >= 4.7 && < 5
    - hostname >= 1.0 && < 1.1
    - http-client >= 0.5.10
    - katip >= 0.5 && < 0.7
    # TODO: Once the releases stabilize, lock in an upper bound.
    # For the time being,
    # I'm fine dealing with upper bound breakages,
    # since I own rollbar-hs.
    - rollbar-hs >= 0.2
    - stm-chans >= 3.0 && < 3.1
    - text >= 1.2 && < 1.3
    - time >= 1.8 && < 1.9
  source-dirs: src
license: BSD3
maintainer: jones3.hardy@gmail.com
name: katip-rollbar
synopsis: Katip scribe that logs to Rollbar
version: 0.3.0.0
